module.exports = {
  apps: [
    {
      name: 'backend',
      script: 'npm',
      args: 'start',
      cwd: './BackEnd',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 1111,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 1111,
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend.log',
      log_file: './logs/backend-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'frontendv2',
      script: 'npm',
      args: 'run dev',
      cwd: './FrontEndV2',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 1113,
      },
      error_file: './logs/frontendv2-error.log',
      out_file: './logs/frontendv2.log',
      log_file: './logs/frontendv2-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'frontend',
      script: 'npm',
      args: 'run dev',
      cwd: './FrontEnd',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 1112,
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend.log',
      log_file: './logs/frontend-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};

